Adding new examples to Falcon for issue #45
idaholab/falcon pull request #123
Opened 2022-12-20 23:38 UTC by wjin33

2022-12-21 00:04 UTC, moosebuild commented
Job [Test](https://civet.inl.gov/job/1273658/) on cec9739 wanted to post the following:

View the site [here](https://mooseframework.inl.gov/falcon/docs/PRs/123/site)

This comment will be updated on new commits.

2022-12-21 19:31 UTC, loganharbour commented
@dschwen, @rpodgorney is on to you now

2022-12-21 19:35 UTC, rpodgorney commented
@dschwen -- what did you do?  Everything is broken!!!!!!

2022-12-23 15:21 UTC, rpodgorney commented on doc/content/examples/rtes_ht.md
> +Reservoir Thermal Energy Storage (RTES), also called Geological Thermal Energy Storage (GeoTES) or Aquifer Thermal Energy Storage (ATES), is the concept of injecting hot fluid into the subsurface for
Please replace

This example demonstartes the MOOSE-based FALCON can obtain the same quantitative results as compared to the [TOUGH3](https://tough.lbl.gov/software/new-release-tough3/) code for the heat transfer and fluid flow coupled problems.

with

This example presents a comparison of results obtained using FALCON to those from the [TOUGH3](https://tough.lbl.gov/software/new-release-tough3/) code for the heat transfer and fluid flow coupled problems.

2022-12-23 15:22 UTC, rpodgorney requested changes
TOUGH misspelled

2022-12-23 15:23 UTC, rpodgorney requested changes
TOUGH misspelled

2022-12-23 15:24 UTC, rpodgorney commented on doc/content/examples/rtes_ht.md
> +The Lower Tuscaloosa formation located at the Cranfield site was chosen as the storage site. [fig:benchmark] shows the geometry and boundary conditions for the two models built for the TOUGH and FALC
TOUGH misspelled

2022-12-23 15:26 UTC, rpodgorney commented on doc/content/examples/rtes_ht.md
> +A typical RTES operation of injection-storage-extraction-rest seasonal cycles were simulated. During the injection season, we inject hot fluid with a constant injection temperature of 180 degree  int
degree should be "degrees C"

2022-12-23 15:29 UTC, rpodgorney commented on doc/content/examples/rtes_ht.md
> +The blue dotted lines show the FALCON prediction with updated input file. The pore pressure at both the injection and extraction wells match each other perfectly. However, the yielded temperature pre
```suggestion
The blue dotted lines show the FALCON prediction with updated input file. The pore pressure at both the injection and extraction wells match each other perfectly. However, the temperature prediction at the extraction well still has significant discrepancy during the storage season as shown in [fig:comparison]. With a careful examination of the two input files, we found this is due to the boundary condition setup of the two wells. The TOUGH solver is based on FDM, and the two wells were realized by two columns of elements with extremly high permeability. While line sinks were used for the FALCON simulations. Following the same boundary treatment as the TOUGH model, two columns of elements were selcted as different blocks as compared to the formation. The material input for these two blocks are 
```

2022-12-23 15:32 UTC, rpodgorney commented on doc/content/examples/rtes_ht.md
> +Reservoir Thermal Energy Storage (RTES), also called Geological Thermal Energy Storage (GeoTES) or Aquifer Thermal Energy Storage (ATES), is the concept of injecting hot fluid into the subsurface for
```suggestion
Reservoir Thermal Energy Storage (RTES), also called Geological Thermal Energy Storage (GeoTES) or Aquifer Thermal Energy Storage (ATES), is the concept of injecting hot fluid into the subsurface formation for energy storage and extracting it for later use. This example provides a comparison between FALCON and the [TOUGH3](https://tough.lbl.gov/software/new-release-tough3/) code for the heat transfer and fluid flow coupled problems and can be used as an example for TOUGH users on how to setup FALCON simulations
```

2022-12-23 15:32 UTC, rpodgorney commented on doc/content/examples/rtes_ht.md
> +The Lower Tuscaloosa formation located at the Cranfield site was chosen as the storage site. [fig:benchmark] shows the geometry and boundary conditions for the two models built for the TOUGH and FALC
```suggestion
The Lower Tuscaloosa formation located at the Cranfield site was chosen as the storage site. [fig:benchmark] shows the geometry and boundary conditions for the two models built for the TOUGH and FALCON solvers, respectively. The formation thickness is about 24 m and is located at a depth of 3000 m.  Given the symmetry of the 5-spot well configuration, a 1/8 TOUGH model and a quarter FALCON model were built. Note the TOUGH is a finite difference method (FDM) based solver while FALCON is a finite element method based solver, the quarter FALCON model has a better convergence rate. The cap-/bed-rock layers of the TOUGH model were replaced by undrained flow boundary conditions and an analytical solution for heat conduction. While cap-/bed-rocks were explicitly simulated in the FALCON model with both no-flux of heat and fluid applied to the top and bottom surfaces. All the side surfaces for both the FALCON and TOUGH models are symmetrical boundaries. 
```

2022-12-23 15:33 UTC, rpodgorney commented on doc/content/examples/rtes_ht.md
> +A typical RTES operation of injection-storage-extraction-rest seasonal cycles were simulated. During the injection season, we inject hot fluid with a constant injection temperature of 180 degree  int
```suggestion
A typical RTES operation of injection-storage-extraction-rest seasonal cycles were simulated. During the injection season, we inject hot fluid with a constant injection temperature of 180 degrees C  into the injection well and extract fluid from the production well at the same fixed rate of 3 kg/s. During the extraction season, we inject cold fluid with the same temperature as the formation initial temperature To = 126 degree C into the injection well and extract fluid from the production well at the same fixed rate of 3 kg/s. No fluid injection or extraction is conducted during the storage and rest seasons. For this problem, we detail the the input file of FALCON int the following section, and the input file for TOUGH3 can be downloaded [here](examples/rtes_benchmark/tough.inp). 
```

2022-12-23 15:44 UTC, rpodgorney commented on doc/content/examples/forge_falcon.md
> +The Frontier Observatory for Research in Geothermal Energy (FORGE) site is a multi-year initiative funded by the U.S. Department of Energy for enhanced geothermal system research and development. Thi
```suggestion
The Frontier Observatory for Research in Geothermal Energy (FORGE) site is a multi-year initiative funded by the U.S. Department of Energy for enhanced geothermal system research and development. This example presents the development of the native state simulation (i.e., pore pressure, stress, and temperature) of the FORGE site using material property values obtained from the site characterization activities. A detailed description can be found in [!cite](liu2022forge).
```

2022-12-23 16:24 UTC, rpodgorney commented on doc/content/examples/mandel.md
> +# Mandel's consolidation
This example is incomplete.  We can allow it to merge now--and I can push @AhmedAlmetwally and @lynnmunday to add more detail

2022-12-29 16:14 UTC, moosebuild commented
Job [Coverage](https://civet.inl.gov/job/1273659/) on cec9739 wanted to post the following:


## Coverage

Coverage did not change

[Full coverage report](https://mooseframework.inl.gov/falcon/docs/PRs/123/coverage)



This comment will be updated on new commits.

2023-01-09 18:53 UTC, wjin33 commented on doc/content/examples/mandel.md
> +# Mandel's consolidation
Let us merge this first and Either those folks or me can update the rest

2023-01-11 18:18 UTC, lynnmunday commented on doc/content/examples/mandel.md
> +# Mandel's consolidation
That is good.

2023-01-17 15:25 UTC, rpodgorney commented
We'll re-review and make any final changes with the next PR

2023-01-17 15:25 UTC, merged