Building the documentation pages
idaholab/falcon pull request #48
Opened 2021-06-04 21:32 UTC by rpodgorney

2021-06-04 22:27 UTC, crswong888 requested changes
Everything looks good to me! just a few changes:

2021-06-04 22:27 UTC, crswong888 commented on doc/content/documentation.menu.md
> +- [Geochemistry](https://mooseframework.inl.gov/modules/geochemistry/theory/index.html)
These pages are already built by Falcon docs, and its better to link to the local content like:

```
- [modules/porous_flow/governing_equations.md]
- [modules/porous_flow/material_laws.md]
- [Fluid Equations of State](modules/porous_flow/fluids.md)
- [Geochemistry](modules/geochemistry/theory/index.md)
```

2021-06-04 22:27 UTC, crswong888 commented on doc/content/documentation.menu.md
> +- [Code Standards](https://mooseframework.inl.gov/sqa/framework_scs.html)
Same thing here, use `- [Code Standards](sqa/framework_scs.md)`

2021-06-04 22:27 UTC, crswong888 commented on doc/content/examples/index.md
> +!media falcon/anim_elder_fe_lv1.mp4
This should work once the [large media commit](https://github.com/idaholab/large_media/commit/06d3b39786410c388f8b47cc016ffd269e4e61cf) is pulled in, which needs to be done in the MOOSE repo.

2021-06-05 21:49 UTC, rpodgorney commented
@crswong888  just pushed revision with recommended changes.  Got errors on 

- [Geochemistry](modules/geochemistry/theory/index.md)

so kept it pointed at the url

2021-06-05 21:56 UTC, merged